---
title: "Blog Post #2"
author: "By Ella Trembanis"
date: '2024-09-15'
output:
  html_document:
    df_print: paged
categories: []
tags: []
slug: "blog-post-2"
---
# Voters & "The Economy"

# Gross Domestic Product (GDP) Growth



```{r set-up, echo=FALSE, include=FALSE, warning=FALSE}
library(ggplot2)
library(tidyverse)

# My custom theme
my_theme <- function() {
  theme(
  # set panel features
  panel.border = element_rect(color = "#000033", fill = NA, linetype = 1),
  panel.background = element_rect(fill = "#FFFFFF"),
  panel.grid.major.x = element_line(color = "#9999CC", linetype = 2, size = 0.2),
  panel.grid.minor.x = element_blank(),
  panel.grid.major.y = element_line(color = "#9999CC", linetype = 2, size = 0.2),
  panel.grid.minor.y = element_blank(),
  # set text and axis features
  text = element_text(color = "#000033", family = "Courier"),
  title = element_text(color = "#000033", face = "bold", family = "Courier"),
  axis.ticks = element_line(color = "#000033"),
  # set legend features
  legend.position = "bottom",
  legend.background = element_rect(color = "#000033", fill = NA, linetype = 1)
  )
}

# Load popular vote data
popvote <- read_csv("/Users/ellatrembanis/Desktop/Gov 1347/election-blog/election-blog/Week2/data/popvote_1948-2020.csv")


# FRED variables:

# GDP, billions $, 1947-2024
# GDP_growth_quarterly, %
# RDPI, $, 1959-2024
# RDPI_growth_quarterly, %
# CPI, $ index, 1947-2024
# unemployment, %, 1948-2024
# sp500_, $, 1927-2024 

# Load Fred
fred <- read_csv("/Users/ellatrembanis/Desktop/Gov 1347/election-blog/election-blog/Week2/data/fred_econ.csv")

# BEA variables:

# GDP, 1947-2024 (all)
# GNP
# RDPI
# Personal consumption expenditures
# Goods
# Durable goods
# Nondurable goods
# Services 
# Population (midperiod, thousands)

# Load Bea
bea <- read_csv("/Users/ellatrembanis/Desktop/Gov 1347/election-blog/election-blog/Week2/data/bea_econ.csv") |> 
  # standardize column names
  rename(year = "Year",
         quarter = "Quarter", 
         gdp = "Gross domestic product", 
         gnp = "Gross national product", 
         dpi = "Disposable personal income", 
         consumption = "Personal consumption expenditures", 
         goods = "Goods", 
         durables = "Durable goods", 
         nondurables = "Nondurable goods", 
         services = "Services", 
         pop = "Population (midperiod, thousands)")

# Filter and Merge

party_econ <- popvote |> 
  # incumbent party vote share only
  filter(incumbent_party == TRUE) |> 
  select(year, pv, pv2p, winner, incumbent) |> 
  # filter to Q2 (most recent available quarter of current year)
  left_join(fred |> filter(quarter == 2)) |> 
  left_join(bea |> filter(quarter == "Q2") |> 
              select(year, dpi))

inc_econ <- popvote |>
  # incumbent (individual) vote share only, omit 2020
  filter(incumbent == TRUE & year != 2020) |>
  select(year, pv, pv2p, winner) |>
  left_join(fred |> 
              filter(quarter == 2)) |>
  left_join(bea |> 
              filter(quarter == "Q2") |>
              select(year, dpi))

heir_econ <- popvote |>
  # incumbent (same-party heir) vote share only
  filter(incumbent_party == TRUE & incumbent == FALSE) |>
  select(year, pv, pv2p, winner) |>
  left_join(fred |>
              filter(quarter == 2)) |>
  left_join(bea |>
              filter(quarter == "Q2") |>
              select(year, dpi))
```

```{r fig 1 code, echo=FALSE, include=FALSE, warning=FALSE}
fig1 <- party_econ |> 
  ggplot(aes(x = GDP_growth_quarterly, y = pv2p, label = year)) + 
  geom_label(aes(family = "Courier")) + 
  geom_smooth(method = "lm", formula = y ~ x, color = "#9999CC") +
  geom_hline(yintercept = 50, lty = 2, color = "#000033") + 
  geom_vline(xintercept = 0.01, lty = 2, color = "#000033") + 
  labs(x = "Second Quarter GDP Growth (%)", 
       y = "Popular Vote Share - Incumbent Party (%)", 
       title = "Fig. I - GDP vs. Vote Share") + 
  my_theme() + 
  theme(plot.title = element_text(size = 14))
```

```{r fig 1 print, echo=FALSE, include=TRUE, warning=FALSE}
fig1
```

```{r fig 2 code, echo=FALSE, include=FALSE, warning=FALSE}
party_econ_omit <- party_econ |>
  # exclude outliers
  filter(year != 2020 & year != 1980)

fig2 <- party_econ_omit |> 
  ggplot(aes(x = GDP_growth_quarterly, y = pv2p, label = year)) + 
  geom_label(aes(family = "Courier")) + 
  geom_smooth(method = "lm", formula = y ~ x, color = "#9999CC") +
  geom_hline(yintercept = 50, lty = 2, color = "#000033") + 
  geom_vline(xintercept = 0.01, lty = 2, color = "#000033") + 
  labs(x = "Second Quarter GDP Growth (%)", 
       y = "Popular Vote Share - Incumbent Party (%)", 
       title = "Fig. II - GDP vs. Vote Share, No Outliers") + 
  my_theme() + 
  theme(plot.title = element_text(size = 14))
```

```{r fig 2 print, echo=FALSE, include=TRUE, warning=FALSE}
fig2
```


# Unemployment

```{r fig 3 code, echo=FALSE, include=FALSE, warning=FALSE}
party_econ_2020 <- party_econ |>
  filter(year != 2020)

fig3 <- party_econ_2020 |> 
  ggplot(aes(x = unemployment, y = pv2p, label = year)) + 
  geom_label(aes(family = "Courier")) + 
  geom_smooth(method = "lm", formula = y ~ x, color = "#9999CC") +
  geom_hline(yintercept = 50, lty = 2, color = "#000033") + 
  geom_vline(xintercept = 0.01, lty = 2, color = "#000033") + 
  labs(x = "Second Quarter Unemployment Rate (%)", 
       y = "Popular Vote Share - Incumbent Party (%)", 
       title = "Fig. III - Unemployment vs. Vote Share, No Outlier") + 
  xlim(2, 9) +
  my_theme() + 
  theme(plot.title = element_text(size = 14))
```

```{r fig 3 print, echo=FALSE, include=TRUE, warning=FALSE}
fig3
```

# Consumer Price Index (CPI)

```{r fig 4 code, echo=FALSE, include=FALSE, warning=FALSE}
fig4 <- party_econ |> 
  ggplot(aes(x = CPI, y = pv2p, label = year)) + 
  geom_label(aes(family = "Courier")) + 
  geom_smooth(method = "lm", formula = y ~ x, color = "#9999CC") +
  geom_hline(yintercept = 50, lty = 2, color = "#000033") + 
  geom_vline(xintercept = 0.01, lty = 2, color = "#000033") + 
  labs(x = "Second Quarter Consumer Price Index", 
       y = "Popular Vote Share - Incumbent Party (%)", 
       title = "Fig. IV - CPI vs. Vote Share") + 
  my_theme() + 
  theme(plot.title = element_text(size = 14))
```

```{r fig 4 print, echo=FALSE, include=TRUE, warning=FALSE}
fig4
```

# Models in Review

```{r table code, echo=FALSE, include=FALSE, warning=FALSE}
predictions <- tibble(Model = c("GDP Growth", "Unemployment", "CPI", "Multiple"),
                 Prediction = c(51.35652, 51.97273, 48.33048, 46.30151),
                 `Lower Bound` = c(41.25755, 39.83306, 35.591, 33.24755),
                 `Upper Bound` = c(61.4555, 64.11241, 61.06995, 59.35547))
```

```{r table print, echo=FALSE, include=TRUE, warning=FALSE}
knitr::kable(predictions, digits = 2)
```

# Prediction, and a Note on Incumbency

```{r fig 5 code, echo=FALSE, include=FALSE, warning=FALSE}
fig5 <- party_econ_omit |> 
  ggplot(aes(x = GDP_growth_quarterly, y = pv2p, label = year, fill = incumbent)) + 
  geom_label(aes(family = "Courier")) + 
  geom_hline(yintercept = 50, lty = 2, color = "#000033") + 
  geom_vline(xintercept = 0.01, lty = 2, color = "#000033") + 
  labs(x = "Second Quarter GDP Growth (%)", 
       y = "Popular Vote Share - Incumbent Party (%)", 
       title = "Fig. V - GDP vs. Vote Share by Incumbent Type") + 
  my_theme() + 
  theme(plot.title = element_text(size = 14))
```

```{r fig 5 print, echo=FALSE, include=TRUE, warning=FALSE}
fig5
```

```{r fig 6 code, echo=FALSE, include=FALSE, warning=FALSE}
fig6 <- party_econ_2020 |> 
  ggplot(aes(x = unemployment, y = pv2p, label = year, fill = incumbent)) + 
  geom_label(aes(family = "Courier")) + 
  geom_smooth(method = "lm", formula = y ~ x, color = "#9999CC") +
  geom_hline(yintercept = 50, lty = 2, color = "#000033") + 
  geom_vline(xintercept = 0.01, lty = 2, color = "#000033") + 
  labs(x = "Second Quarter Unemployment Rate (%)", 
       y = "Popular Vote Share - Incumbent Party (%)", 
       title = "Fig. VI - Unemployment vs. Vote Share by Incumbent Type") + 
  my_theme() + 
  theme(plot.title = element_text(size = 14))
```

```{r fig 6 print, echo=FALSE, include=TRUE, warning=FALSE}
fig6
```
