---
title: "week10-section"
author: "Ella Trembanis"
date: "2024-11-13"
output: html_document
---

# Set-Up

```{r load library}
library(censable)
library(geofacet)
library(ggpubr)
library(ggthemes)
library(haven)
library(kableExtra)
library(maps)
library(mgcv)
library(mgcViz)
library(RColorBrewer)
library(readstata13)
library(scales)
library(sf)
library(spData)
library(stargazer)
library(tidygeocoder)
library(tidyverse)
library(tigris)
library(tmap)
library(tmaptools)
library(viridis)
```

```{r custom theme, echo=FALSE, include=FALSE, warning=FALSE}
my_theme <- function() {
  theme(
  # set panel features
  panel.border = element_rect(color = "#000033", fill = NA, linetype = 1),
  panel.background = element_rect(fill = "#FFFFFF"),
  panel.grid.major.x = element_line(color = "#9999CC", linetype = 2, size = 0.2),
  panel.grid.minor.x = element_blank(),
  panel.grid.major.y = element_line(color = "#9999CC", linetype = 2, size = 0.2),
  panel.grid.minor.y = element_blank(),
  # set text and axis features
  text = element_text(color = "#000033", family = "Courier"),
  title = element_text(color = "#000033", face = "bold", family = "Courier"),
  axis.ticks = element_line(color = "#000033"),
  # set legend features
  legend.position = "bottom",
  legend.background = element_rect(color = "#000033", fill = NA, linetype = 1)
  )
}
```

```{r simplified custom theme, echo=FALSE, include=FALSE, warning=FALSE}
my_map_theme <- function() {
  theme(
    # set panel features
    panel.background = element_rect(fill = "#FFFFFF"),
    # set text features
    text = element_text(color = "#000033", family = "Courier"),
    title = element_text(color = "#000033", face = "bold", family = "Courier"),
    # set legend features
    legend.position = "bottom",
    legend.title.position = "top",
    legend.background = element_rect(color = "#000033", fill = NA, linetype = 1),
    # set axis features to not display
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank()
  )
}
```

```{r read data}
# Read 2024 results datasets. 
d_state_2024 <- read_csv("/Users/ellatrembanis/Desktop/Gov 1347/election-blog/election-blog/Week10/data/state_votes_pres_2024.csv")[-1, 1:6]
d_county_2024 <- read_csv("/Users/ellatrembanis/Desktop/Gov 1347/election-blog/election-blog/Week10/data/county_votes_pres_2024.csv")[-1, 1:6]
d_county_2020 <- read_csv("/Users/ellatrembanis/Desktop/Gov 1347/election-blog/election-blog/Week10/data/county_votes_pres_2020.csv")[-1, 1:6]

# Process 2024 state and county-level data. 
d_state_2024 <- d_state_2024 |> 
  mutate(FIPS = as.numeric(FIPS), 
         votes_trump = as.numeric(`Donald J. Trump`), 
         votes_harris = as.numeric(`Kamala D. Harris`), 
         votes = as.numeric(`Total Vote`), 
         trump_pv = votes_trump/votes, 
         harris_pv = votes_harris/votes, 
         trump_2pv = votes_trump/(votes_trump + votes_harris), 
         harris_2pv = votes_harris/(votes_trump + votes_harris)) |> 
  mutate(winner = case_when(votes_trump > votes_harris ~ "REP", 
                            .default = "DEM")) |> 
  select(FIPS, `Geographic Name`, `Geographic Subtype`, votes_trump, votes_harris, votes, 
         winner, trump_pv, harris_pv, trump_2pv, harris_2pv)

d_county_2024 <- d_county_2024 |>
  mutate(FIPS = as.numeric(FIPS),
         votes_trump = as.numeric(`Donald J. Trump`), 
         votes_harris = as.numeric(`Kamala D. Harris`), 
         votes = as.numeric(`Total Vote`), 
         trump_pv = votes_trump/votes, 
         harris_pv = votes_harris/votes, 
         trump_2pv = votes_trump/(votes_trump + votes_harris), 
         harris_2pv = votes_harris/(votes_trump + votes_harris)) |> 
  mutate(winner = case_when(votes_trump > votes_harris ~ "REP", 
                            .default = "DEM")) |> 
  select(FIPS, `Geographic Name`, `Geographic Subtype`, votes_trump, votes_harris, votes, 
         winner, trump_pv, harris_pv, trump_2pv, harris_2pv)

d_county_2020 <- d_county_2020 |> 
  mutate(FIPS = as.numeric(FIPS),
         votes_trump_2020 = as.numeric(`Donald J. Trump`), 
         votes_biden_2020 = as.numeric(`Joseph R. Biden Jr.`), 
         votes_2020 = as.numeric(`Total Vote`), 
         trump_pv_2020 = votes_trump_2020/votes_2020, 
         biden_pv_2020 = votes_biden_2020/votes_2020, 
         trump_2pv_2020 = votes_trump_2020/(votes_trump_2020 + votes_biden_2020), 
         biden_2pv_2020 = votes_biden_2020/(votes_trump_2020 + votes_biden_2020)) |> 
  mutate(winner_2020 = case_when(votes_trump_2020 > votes_biden_2020 ~ "REP", 
                            .default = "DEM")) |> 
  select(FIPS, `Geographic Name`, `Geographic Subtype`, votes_trump_2020, votes_biden_2020, votes_2020, 
         winner_2020, trump_pv_2020, biden_pv_2020, trump_2pv_2020, biden_2pv_2020)
```

# Visualization

```{r map set-up}
# Sequester state and county-level map.
states_2024 <- states(cb = TRUE, year = 2023) |> 
  shift_geometry() |> 
  mutate(GEOID = as.numeric(GEOID)) |> 
  left_join(d_state_2024, by = c("GEOID" = "FIPS")) |> 
  drop_na()
counties_2024 <- counties(cb = TRUE, resolution = "5m", year = 2023) |> 
  shift_geometry() |> 
  mutate(GEOID = as.numeric(GEOID)) |> 
  left_join(d_county_2024, by = c("GEOID" = "FIPS")) |> 
  left_join(d_county_2020, by = c("GEOID" = "FIPS")) |>
  mutate(shift = (trump_pv - trump_pv_2020) * 100, 
         shift_dir = case_when(shift > 0 ~ "REP", 
                               shift < 0 ~ "DEM", 
                               TRUE ~ "No Change"),
         centroid = st_centroid(geometry), 
         centroid_long = st_coordinates(centroid)[,1],
         centroid_lat = st_coordinates(centroid)[,2],
         scale_factor = 1e4, 
         end_long = centroid_long + scale_factor * shift,
         end_lat = centroid_lat + scale_factor * shift) |>
  drop_na()
county_pop_2024 <- read_csv("/Users/ellatrembanis/Desktop/Gov 1347/election-blog/election-blog/Week10/data/PopulationEstimates.csv") |> 
  mutate(FIPStxt = as.numeric(FIPStxt)) |>
  select(FIPStxt, POP_ESTIMATE_2023)
counties_2024 <- counties_2024 |> 
  left_join(county_pop_2024, by = c("GEOID" = "FIPStxt"))
```

```{r state win map}
# Make map of state winners. 
ggplot(states_2024, aes(fill = factor(winner))) + 
  geom_sf(color = "#000033") + 
  scale_fill_manual(values = c("DEM" = "#7CB9E8", "REP" = "#FF6680")) + 
  my_map_theme() + 
  labs(title = "2024 Presidential Election Results by State", 
       fill = "Winner") + 
  theme(legend.position = "bottom") 
```

```{r county win map}
# Make map of county winners.
ggplot(counties_2024, aes(fill = factor(winner))) + 
  geom_sf(color = "#000033") + 
  scale_fill_manual(values = c("DEM" = "#7CB9E8", "REP" = "#FF6680")) + 
  my_map_theme() + 
  labs(title = "2024 Presidential Election Results by County", 
       fill = "Winner") + 
  theme(legend.position = "bottom")
```

```{r county bubble map}
# Make bubble map of county-level results for the US for 2024. 
counties_2024 |> 
  ggplot() + 
  geom_sf(fill = "#FCFCFC", color = "#9999CC") +  # Base map
  geom_point(aes(x = centroid_long, y = centroid_lat, size = POP_ESTIMATE_2023, color = factor(winner)),
             alpha = 0.7) +  # Semi-transparent bubbles
  scale_size_continuous(range = c(1, 10), breaks = c(10000, 100000, 500000, 1000000),
                        labels = scales::comma) +  # Scale bubble size proportionally to population
  scale_color_manual(values = c("DEM" = "#7CB9E8", "REP" = "#FF6680")) +  # Color by party
  my_map_theme() +
  labs(title = "2024 Presidential Election Results by County",
       subtitle = "(Bubble size represents county population)",
       size = "Population",
       color = "Winner") +
  theme(legend.position = "right")
```

```{r county arrow map}
# Make arrow map of county-level shifts across US. 
counties_2024$shift |> mean()
counties_2024 |> 
  ggplot() +
  geom_sf(fill = "#FCFCFC", color = "#9999CC") +  # Base map
  geom_curve(aes(x = centroid_long, 
                 y = centroid_lat,
                 xend = end_long, 
                 yend = end_lat,
                 color = shift_dir),
              arrow = arrow(length = unit(0.1, "cm"), type = "closed"),  # Smaller arrowhead
              curvature = 0.2,  # Add a slight curve to each arrow
              size = 0.2) +
  scale_color_manual(values = c("DEM" = "#7CB9E8", "REP" = "#FF6680")) +
  my_map_theme() +
  labs(title = "Presidential Voting Shifts by County Across the US",
       subtitle = "Democratic vs. Republican Gains")
```

```{r pa county map}
# Check county-level shifts in Pennsylvania between 2024 and 2020. 
counties_2024 |> 
  filter(STATE_NAME == "Pennsylvania") |> 
  ggplot() +
  geom_sf(fill = "#FCFCFC", color = "#000033") +  # Base map
  geom_curve(aes(x = centroid_long, 
                 y = centroid_lat,
                 xend = end_long, 
                 yend = end_lat,
                 color = shift_dir),
             arrow = arrow(length = unit(0.1, "cm"), type = "closed"),  # Smaller arrowhead
             curvature = 0.2,  # Add a slight curve to each arrow
             size = 0.3) +
  scale_color_manual(values = c("DEM" = "#7CB9E8", "REP" = "#FF6680")) +
  my_map_theme() +
  labs(title = "Presidential Voting Shifts by County in Pennsylvania",
       subtitle = "Democratic vs. Republican Gains")
```

```{r az county map}
# Check county-level shifts in Arizona between 2024 and 2020. 
counties_2024 |> 
  filter(STATE_NAME == "Arizona") |> 
  ggplot() +
  geom_sf(fill = "#FCFCFC", color = "#000033") +  # Base map
  geom_text(aes(x = centroid_long, y = centroid_lat-1.5e4, label = NAME),
            size = 2,  # Adjust size as needed
            color = "black", hjust = 0.5, vjust = -0.5) + 
  geom_curve(aes(x = centroid_long, 
                 y = centroid_lat,
                 xend = end_long, 
                 yend = end_lat,
                 color = shift_dir),
             arrow = arrow(length = unit(0.1, "cm"), type = "closed"),  # Smaller arrowhead
             curvature = 0.2,  # Add a slight curve to each arrow
             size = 0.3) +
  scale_color_manual(values = c("DEM" = "#7CB9E8", "REP" = "#FF6680")) +
  my_map_theme() +
  labs(title = "Presidential Voting Shifts by County in Arizona",
       subtitle = "Democratic vs. Republican Gains")
```

```{r nv county map}
# Check county-level shifts in Nevada between 2024 and 2020. 
counties_2024 |> 
  filter(STATE_NAME == "Nevada") |> 
  ggplot() +
  geom_sf(fill = "#FCFCFC", color = "#000033") +  # Base map
  geom_curve(aes(x = centroid_long, 
                 y = centroid_lat,
                 xend = end_long, 
                 yend = end_lat,
                 color = shift_dir),
             arrow = arrow(length = unit(0.1, "cm"), type = "closed"),  # Smaller arrowhead
             curvature = 0.2,  # Add a slight curve to each arrow
             size = 0.3) +
  scale_color_manual(values = c("DEM" = "#7CB9E8", "REP" = "#FF6680")) +
  my_map_theme() +
  labs(title = "Presidential Voting Shifts by County in Nevada",
       subtitle = "Democratic vs. Republican Gains")
```

```{r fl county map}
# Check county-level shifts in Florida between 2024 and 2020. 
counties_2024 |> 
  filter(STATE_NAME == "Florida") |> 
  ggplot() +
  geom_sf(fill = "#FCFCFC", color = "#000033") +  # Base map
  geom_curve(aes(x = centroid_long, 
                 y = centroid_lat,
                 xend = end_long, 
                 yend = end_lat,
                 color = shift_dir),
             arrow = arrow(length = unit(0.1, "cm"), type = "closed"),  # Smaller arrowhead
             curvature = 0.2,  # Add a slight curve to each arrow
             size = 0.3) +
  scale_color_manual(values = c("DEM" = "#7CB9E8", "REP" = "#FF6680")) +
  my_map_theme() +
  labs(title = "Presidential Voting Shifts by County in Florida",
       subtitle = "Democratic vs. Republican Gains")
```

```{r ca county map}
# Check county-level shifts in California between 2024 and 2020. 
counties_2024 |> 
  filter(STATE_NAME == "California") |> 
  ggplot() +
  geom_sf(fill = "#FCFCFC", color = "#000033") +  # Base map
  geom_curve(aes(x = centroid_long, 
                 y = centroid_lat,
                 xend = end_long, 
                 yend = end_lat,
                 color = shift_dir),
             arrow = arrow(length = unit(0.1, "cm"), type = "closed"),  # Smaller arrowhead
             curvature = 0.2,  # Add a slight curve to each arrow
             size = 0.3) +
  scale_color_manual(values = c("DEM" = "#7CB9E8", "REP" = "#FF6680")) +
  my_map_theme() +
  labs(title = "Presidential Voting Shifts by County in California",
       subtitle = "Democratic vs. Republican Gains")
```

```{r mi county map}
# Check county-level shifts in Michigan between 2024 and 2020. 
counties_2024 |> 
  filter(STATE_NAME == "Michigan") |> 
  ggplot() +
  geom_sf(fill = "#FCFCFC", color = "#000033") +  # Base map
  geom_curve(aes(x = centroid_long, 
                 y = centroid_lat,
                 xend = end_long, 
                 yend = end_lat,
                 color = shift_dir),
             arrow = arrow(length = unit(0.1, "cm"), type = "closed"),  # Smaller arrowhead
             curvature = 0.2,  # Add a slight curve to each arrow
             size = 0.3) +
  scale_color_manual(values = c("DEM" = "#7CB9E8", "REP" = "#FF6680")) +
  my_map_theme() +
  labs(title = "Presidential Voting Shifts by County in Michigan",
       subtitle = "Democratic vs. Republican Gains")
```

```{r wi county map}
# Check county-level shifts in Wisconsin between 2024 and 2020. 
counties_2024 |> 
  filter(STATE_NAME == "Wisconsin") |> 
  ggplot() +
  geom_sf(fill = "#FCFCFC", color = "#000033") +  # Base map
  geom_curve(aes(x = centroid_long, 
                 y = centroid_lat,
                 xend = end_long, 
                 yend = end_lat,
                 color = shift_dir),
             arrow = arrow(length = unit(0.1, "cm"), type = "closed"),  # Smaller arrowhead
             curvature = 0.2,  # Add a slight curve to each arrow
             size = 0.3) +
  scale_color_manual(values = c("DEM" = "#7CB9E8", "REP" = "#FF6680")) +
  my_map_theme() +
  labs(title = "Presidential Voting Shifts by County in Wisconsin",
       subtitle = "Democratic vs. Republican Gains")
```

```{r ga county map}
# Check county-level shifts in Georgia between 2024 and 2020. 
counties_2024 |> 
  filter(STATE_NAME == "Georgia") |> 
  ggplot() +
  geom_sf(fill = "#FCFCFC", color = "#000033") +  # Base map
  geom_curve(aes(x = centroid_long, 
                 y = centroid_lat,
                 xend = end_long, 
                 yend = end_lat,
                 color = shift_dir),
             arrow = arrow(length = unit(0.1, "cm"), type = "closed"),  # Smaller arrowhead
             curvature = 0.2,  # Add a slight curve to each arrow
             size = 0.3) +
  scale_color_manual(values = c("DEM" = "#7CB9E8", "REP" = "#FF6680")) +
  my_map_theme() +
  labs(title = "Presidential Voting Shifts by County in Georgia",
       subtitle = "Democratic vs. Republican Gains")
```

```{r nc county map}
# Check county-level shifts in North Carolina between 2024 and 2020. 
counties_2024 |> 
  filter(STATE_NAME == "North Carolina") |> 
  ggplot() +
  geom_sf(fill = "#FCFCFC", color = "#000033") +  # Base map
  geom_curve(aes(x = centroid_long, 
                 y = centroid_lat,
                 xend = end_long, 
                 yend = end_lat,
                 color = shift_dir),
             arrow = arrow(length = unit(0.1, "cm"), type = "closed"),  # Smaller arrowhead
             curvature = 0.2,  # Add a slight curve to each arrow
             size = 0.3) +
  scale_color_manual(values = c("DEM" = "#7CB9E8", "REP" = "#FF6680")) +
  my_map_theme() +
  labs(title = "Presidential Voting Shifts by County in North Carolina",
       subtitle = "Democratic vs. Republican Gains")
```

```{r de county map}
# Check county-level shifts in Delaware between 2024 and 2020. 
counties_2024 |> 
  filter(STATE_NAME == "Delaware") |> 
  ggplot() +
  geom_sf(fill = "#FCFCFC", color = "#000033") +  # Base map
  geom_label(aes(x = centroid_long, y = centroid_lat-1e4, label = NAME),
            size = 2,  # Adjust size as needed
            color = "black", hjust = 0.5, vjust = -0.005) + 
  geom_curve(aes(x = centroid_long, 
                 y = centroid_lat,
                 xend = end_long, 
                 yend = end_lat,
                 color = shift_dir),
             arrow = arrow(length = unit(0.1, "cm"), type = "closed"),  # Smaller arrowhead
             curvature = 0.2,  # Add a slight curve to each arrow
             size = 0.3) +
  scale_color_manual(values = c("DEM" = "#7CB9E8", "REP" = "#FF6680")) +
  my_map_theme() +
  labs(title = "Presidential Voting Shifts by County in Delaware",
       subtitle = "Democratic vs. Republican Gains")
```

```{r ne county map}
# Check county-level shifts in Nebraska between 2024 and 2020. 
counties_2024 |> 
  filter(STATE_NAME == "Nebraska") |> 
  ggplot() +
  geom_sf(fill = "#FCFCFC", color = "#000033") +  # Base map
  geom_label(aes(x = centroid_long, y = centroid_lat-1e4, label = NAME),
            size = 2,  # Adjust size as needed
            color = "black", hjust = 0.5, vjust = -0.005) + 
  geom_curve(aes(x = centroid_long, 
                 y = centroid_lat,
                 xend = end_long, 
                 yend = end_lat,
                 color = shift_dir),
             arrow = arrow(length = unit(0.1, "cm"), type = "closed"),  # Smaller arrowhead
             curvature = 0.2,  # Add a slight curve to each arrow
             size = 0.3) +
  scale_color_manual(values = c("DEM" = "#7CB9E8", "REP" = "#FF6680")) +
  my_map_theme() +
  labs(title = "Presidential Voting Shifts by County in Nebraska",
       subtitle = "Democratic vs. Republican Gains")
```

