---
title: 'Blog Post #3'
author: "By Ella Trembanis"
date: '2024-09-22'
output:
  html_document:
    df_print: paged
categories: []
tags: []
slug: "blog-post-3"
---

# Polls and Campaign Narratives

```{r load libraries, echo=FALSE, include=FALSE, warning=FALSE}
library(car)
library(caret)
library(CVXR)
library(glmnet)
library(tidyverse)
library(ggplot2)
library(mice)
```

```{r custom theme, echo=FALSE, include=FALSE, warning=FALSE}
my_theme <- function() {
  theme(
  # set panel features
  panel.border = element_rect(color = "#000033", fill = NA, linetype = 1),
  panel.background = element_rect(fill = "#FFFFFF"),
  panel.grid.major.x = element_line(color = "#9999CC", linetype = 2, size = 0.2),
  panel.grid.minor.x = element_blank(),
  panel.grid.major.y = element_line(color = "#9999CC", linetype = 2, size = 0.2),
  panel.grid.minor.y = element_blank(),
  # set text and axis features
  text = element_text(color = "#000033", family = "Courier"),
  title = element_text(color = "#000033", face = "bold", family = "Courier"),
  axis.ticks = element_line(color = "#000033"),
  # set legend features
  legend.position = "bottom",
  legend.background = element_rect(color = "#000033", fill = NA, linetype = 1)
  )
}
```

```{r read data, echo=FALSE, include=FALSE, warning=FALSE}
# processed FiveThirtyEight polling average datasets
nat_poll <- read_csv("/Users/ellatrembanis/Desktop/Gov 1347/election-blog/election-blog/Blog #3/data/national_polls_1968-2024.csv")
state_poll <- read_csv("/Users/ellatrembanis/Desktop/Gov 1347/election-blog/election-blog/Blog #3/data/national_polls_1968-2024.csv")

# national popular vote
nat_vote <- read_csv("/Users/ellatrembanis/Desktop/Gov 1347/election-blog/election-blog/Blog #3/data/popvote_1948-2020.csv") |>
  filter(year >= 1968) |>
  select(year, party, pv2p, pv)
nat_vote$party[nat_vote$party == "democrat"] <- "DEM"
nat_vote$party[nat_vote$party == "republican"] <- "REP"

# state popular vote
state_vote <- read_csv("/Users/ellatrembanis/Desktop/Gov 1347/election-blog/election-blog/Blog #3/data/clean_wide_state_2pv_1948_2020.csv") |>
  filter(year >= 1968) |>
  select(year, state, D_pv2p, R_pv2p) |>
  pivot_longer(
    cols = D_pv2p:R_pv2p,
    cols_vary = "fastest",
    names_to = ("party")
  )
state_vote$party[state_vote$party == "D_pv2p"] <- "DEM"
state_vote$party[state_vote$party == "R_pv2p"] <- "REP"
state_vote$pv2p <- state_vote$value

state_vote <- state_vote |>
  select(year, state, party, pv2p)

# economic data
econ <- read_csv("/Users/ellatrembanis/Desktop/Gov 1347/election-blog/election-blog/Blog #3/data/fred_econ.csv") |> 
# filter to most recent available quarter of 2024
  filter(quarter == 2)
```


```{r fig 1 code, echo=FALSE, include=FALSE, warning=FALSE}
fig1 <- nat_poll |> 
  filter(year == 2024) |> 
  ggplot(aes(x = poll_date, y = poll_support, color = party)) +
  geom_point(size = 1) + 
  geom_line() + 
  scale_x_date(date_labels = "%b %d") + 
  scale_color_manual(values = c("dodgerblue4", "firebrick1")) +
  labs(x = "Date",
       y = "Average Poll Approval", 
       title = "Fig. I - Polling Averages by Date, 2024") + 
  geom_rect(xmin=as.Date("2024-08-19"), xmax=as.Date("2024-08-22"), ymin=45, ymax=48.5, alpha=0.02, colour=NA, fill="#9999CC") +
  annotate("label", x=as.Date("2024-08-20"), y=48, label="DNC", size=4, family = "Courier") +
  geom_rect(xmin=as.Date("2024-07-15"), xmax=as.Date("2024-07-18"), ymin=41.7, ymax=45, alpha=0.02, colour=NA, fill="#9999CC") +
  annotate("label", x=as.Date("2024-07-16"), y=44, label="RNC", size=4, family = "Courier") +
  geom_segment(x = as.Date("2024-06-27"), xend = as.Date("2024-06-27"), y = 41, yend = 46, linetype = "dashed", alpha = 0.4, color = "#9999CC") +
  annotate("label", x = as.Date("2024-06-27"), y = 46, label = "Biden-Trump\nDebate", size = 3, family = "Courier") +
  geom_segment(x = as.Date("2024-07-11"), xend = as.Date("2024-07-11"), y = 40.2, yend = 41.3, linetype = "dashed", alpha = 0.4, color = "#9999CC") +
  annotate("label", x = as.Date("2024-07-11"), y = 41.3, label = "Putin\nGaffe", size = 3, family = "Courier") +
  geom_segment(x = as.Date("2024-07-13"), xend = as.Date("2024-07-13"), y = 42.2, yend = 45, linetype = "dashed", alpha = 0.4, color = "#9999CC") +
  annotate("label", x = as.Date("2024-07-13"), y = 45, label = "Trump Shot", size = 3, family = "Courier") +
  geom_segment(x = as.Date("2024-07-21"), xend = as.Date("2024-07-21"), y = 39, yend = 40.2, linetype = "dashed", alpha = 0.4, color = "#9999CC") +
  annotate("label", x = as.Date("2024-07-21"), y = 39, label = "Biden Drops Out", size = 3, family = "Courier") +
  geom_segment(x = as.Date("2024-03-30"), xend = as.Date("2024-03-30"), y = 43.1, yend = 44.8, linetype = "dashed", alpha = 0.4, color = "#9999CC") +
  annotate("label", x = as.Date("2024-03-30"), y = 44.8, label = "Trump Convicted", size = 3, family = "Courier") +
  geom_segment(x = as.Date("2024-08-23"), xend = as.Date("2024-08-23"), y = 47.2, yend = 42.4, linetype = "dashed", alpha = 0.4, color = "#9999CC") +
  annotate("label", x = as.Date("2024-08-23"), y = 42.4, label = "RFK Jr\nDrops Out", size = 3, family = "Courier") +
  geom_segment(x = as.Date("2024-09-10"), xend = as.Date("2024-09-10"), y = 48.2, yend = 45.7, linetype = "dashed", alpha = 0.4, color = "#9999CC") +
  annotate("label", x = as.Date("2024-09-10"), y = 46.6, label = "Trump-Harris\nDebate", size = 3, family = "Courier") +
  my_theme()
```

```{r fig 1 print, echo=FALSE, include=TRUE, warning=FALSE}
fig1
```

```{r week-by-week, echo=FALSE, include=FALSE, warning=FALSE}
# use weeks left as columns
week_poll <- nat_poll |> 
  group_by(year, party, weeks_left) |>
  summarize(mean_poll_week = mean(poll_support)) |> 
  filter(weeks_left <= 30) |> 
  pivot_wider(names_from = weeks_left, values_from = mean_poll_week) |>
# merge national vote
  left_join(nat_vote, by = c("year", "party"))

# split to train and test
week_poll_train <- week_poll |> 
  filter(year <= 2020)
week_poll_test <- week_poll |> 
  filter(year == 2024)

# rename
colnames(week_poll)[3:33] <- paste0("poll_weeks_left_", 0:30)
colnames(week_poll_train)[3:33] <- paste0("poll_weeks_left_", 0:30)
colnames(week_poll_test)[3:33] <- paste0("poll_weeks_left_", 0:30)

# define x (polls by weeks left) and y (popular vote)
x.train <- week_poll_train |>
  ungroup() |> 
  select(all_of(starts_with("poll_weeks_left_"))) |> 
  as.matrix()
y.train <- week_poll_train$pv2p

# ols
ols.weekpoll <- lm(paste0("pv2p ~ ", paste0( "poll_weeks_left_", 0:30, collapse = " + ")), 
                    data = week_poll_train)
# set ridge using alpha = 0
ridge.weekpoll <- glmnet(x = x.train, y = y.train, alpha = 0)
# set lasso using alpha = 1
lasso.weekpoll <- glmnet(x = x.train, y = y.train, alpha = 1) 
# set elastic net using alpha = 0.5
enet.weekpoll <- glmnet(x = x.train, y = y.train, alpha = 0.5) 

# cross-validate
set.seed(19709)
cv.ridge.weekpoll <- cv.glmnet(x = x.train, y = y.train, alpha = 0)
set.seed(19709)
cv.lasso.weekpoll <- cv.glmnet(x = x.train, y = y.train, alpha = 1)
set.seed(19709)
cv.enet.weekpoll <- cv.glmnet(x = x.train, y = y.train, alpha = 0.5)

# retrieve optimized lambdas
lambda.min.ridge <- cv.ridge.weekpoll$lambda.min
lambda.min.lasso <- cv.lasso.weekpoll$lambda.min
lambda.min.enet <- cv.enet.weekpoll$lambda.min

# compare mean-squared error
mse.ridge <- mean((predict(ridge.weekpoll, s = lambda.min.ridge, newx = x.train) - y.train)^2) #9.575001
mse.lasso <- mean((predict(lasso.weekpoll, s = lambda.min.lasso, newx = x.train) - y.train)^2) #4.681366
mse.enet <- mean((predict(enet.weekpoll, s = lambda.min.enet, newx = x.train) - y.train)^2) #4.302942

# generate coefficient plot to compare regularization methods
coefplot <- data.frame("OLS" = coef(ols.weekpoll)[-1],
                       "Ridge" = coef(ridge.weekpoll, s = lambda.min.ridge)[-1], 
                         "Lasso" = coef(lasso.weekpoll, s = lambda.min.lasso)[-1], 
                         "Elastic Net" = coef(enet.weekpoll, s = lambda.min.enet)[-1]) |> 
  rownames_to_column("coef_name") |> 
  pivot_longer(cols = -coef_name, names_to = "method", values_to = "coef_est") |> 
  mutate(week = rep(0:30, each = 4))

coefplot[which(is.na(coefplot$coef_est)),]$coef_est <- 0 

fig2 <- coefplot |>
  ggplot(aes(x = coef_est, y = reorder(coef_name, -week), color = method)) +
  geom_segment(aes(xend = 0, yend = reorder(coef_name, -week)), alpha = 0.5, lty = "dashed") +
  geom_vline(aes(xintercept = 0), lty = "dashed") +   
  geom_point() + 
  labs(x = "Coefficient Estimate", 
       y = "Weeks Left", 
       title = "Fig II. - Coefficients Across Regularization Methods") + 
  my_theme() +
  theme(
     panel.grid.major.x = element_blank(),
     panel.grid.major.y = element_blank(),
     axis.text.y = element_blank(),
     axis.ticks.y = element_blank()
  )

# enet prediction

x.train <- week_poll_train |>
  ungroup() |> 
# select weeks 7-30 left to maximize coverage (we are 7 weeks away)
  select(all_of(paste0("poll_weeks_left_", 7:30))) |> 
  as.matrix()
# train and test sets
y.train <- week_poll_train$pv2p
x.test <- week_poll_test |>
  ungroup() |> 
  select(all_of(paste0("poll_weeks_left_", 7:30))) |> 
  as.matrix()
# create enet for selected weeks
set.seed(19709)
enet.poll <- cv.glmnet(x = x.train, y = y.train, alpha = 0.5)
lambda.min.enet.poll <- enet.poll$lambda.min

#predict
polls.pred <- predict(enet.poll, s = lambda.min.enet.poll, newx = x.test)
# Harris 51.81%
# Trump 50.58%

# weight on proximity to election day
election_day_2024 <- "2024-11-05"
today <- "2024-09-22"
days_left <- as.numeric(as.Date(election_day_2024) - as.Date(today))

(poll_model_weight <- 1- (1/sqrt(days_left)))
(fund_model_weight <- 1/sqrt(days_left))

proximity.pred <- polls.pred * poll_model_weight
# Harris 44.0
# Trump 42.95

# merge, create vote lags. 
combined <- econ |> 
  left_join(week_poll, by = "year") |> 
  filter(year %in% c(unique(nat_vote$year), 2024)) |> 
  group_by(party) |> 
  mutate(pv2p_lag1 = lag(pv2p, 1), 
         pv2p_lag2 = lag(pv2p, 2)) |> 
  ungroup()

# fundamentals-only dataset
fund <- combined |> 
  select("year", "pv2p", "GDP_growth_quarterly", "pv2p_lag1", "pv2p_lag2") 
# split to train and test
x.train.fund <- fund |> 
  filter(year <= 2020) |>
  select(-c(year, pv2p)) |> 
  slice(-c(1:9)) |> 
  as.matrix()
y.train.fund <- fund |> 
  filter(year <= 2020) |> 
  select(pv2p) |> 
  slice(-c(1:9)) |> 
  as.matrix()
x.test.fund <- fund |> 
  filter(year == 2024) |> 
  select(-c(year, pv2p)) |> 
  drop_na() |> 
  as.matrix()

# fundamentals-only ols
lm.fund <- lm(y.train.fund ~ x.train.fund)
lm.fund.pred <- predict(lm.fund, newx = x.test.fund)
# Harris 51.93%
# Trump 47.42%

# run fundamentals-only enet (note: prediction is the same as ols, since only one economic variable is used -- enet is only used to facilitate combination with other models below)
set.seed(02138)
enet.fund <- cv.glmnet(x = x.train.fund, y = y.train.fund, intercept = FALSE, alpha = 0.5)
lambda.min.enet.fund <- enet.fund$lambda.min
enet.fund.pred <- predict(enet.fund, s = lambda.min.enet.fund, newx = x.test.fund)

# Sequester data for combined model.
combo <- combined |> 
  select("year", "pv2p", "GDP_growth_quarterly", "pv2p_lag1", "pv2p_lag2", all_of(paste0("poll_weeks_left_", 7:30))) 

x.train.combined <- combo |> 
  filter(year <= 2020) |> 
  select(-c(year, pv2p)) |> 
  slice(-c(1:9)) |> 
  as.matrix()
y.train.combined <- combo |>
  filter(year <= 2020) |> 
  select(pv2p) |> 
  slice(-c(1:9)) |> 
  as.matrix()
x.test.combined <- combo |>
  filter(year == 2024) |> 
  select(-c(year, pv2p)) |> 
  drop_na() |> 
  as.matrix()

# combined enet
set.seed(02138)
enet.combined <- cv.glmnet(x = x.train.combined, y = y.train.combined, intercept = FALSE, alpha = 0.5)
lambda.min.enet.combined <- enet.combined$lambda.min

# predict combo
combo.pred <- predict(enet.combined, s = lambda.min.enet.combined, newx = x.test.combined)
# Harris 51.98%
# Trump 47.94%

# combo - polls weighted on proximity, fundamentals not adjusted
ensemble.2.pred <- (proximity.pred + enet.fund.pred)/2
# Harris 47.96%
# Trump 45.19%
```

```{r fig 2 print, echo=FALSE, include=TRUE, warning=FALSE}
fig2
```

```{r table code, echo=FALSE, include=FALSE, warning=FALSE}
predictions <- tibble(Model = c("Polls by Week (A)", "Polls by Proximity (B)", "GDP Growth (C)", "Combined (AC)",
                                "Combined (BC)"),
                      Harris = c(51.81, 44.0, 51.93, 51.98, 47.96),
                      Trump = c(50.58, 42.95, 47.42, 47.94, 45.19))
```

```{r table print, echo=FALSE, include=TRUE, warning=FALSE}
knitr::kable(predictions, digits = 2, caption = "Fig. III - Two-Party Vote Share Predictions")
```

